SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
LEVEL_WIDTH = 1000
LEVEL_HEIGHT = 1000
TERRAIN_SPRITE_SIZE = 32
TERRAIN_TILE_SIZE = 16
LEVEL_MAX_X = LEVEL_WIDTH * TERRAIN_SPRITE_SIZE
LEVEL_MAX_Y = LEVEL_HEIGHT * TERRAIN_SPRITE_SIZE
